### ISSUE TITLE
product properties value size increment

### ISSUE THREAD

**Issue by sunilkumarnagoore** [spree/spree#10175]
Hi,
i want add a large value for product properties but i am getting the below error how i can solve this erorr
![image](https://user-images.githubusercontent.com/43987236/82526352-7244f700-9b51-11ea-85c7-a49c453363e8.png)

**Comment by flobby** [comment]
This would have a terrible impact on all property values since the database would bloat and this might affect overall performance.

Properties are meant to be short and key/value like facts/attributes that describe your product.

It might be an idea to extend your product model with another field? If it is variant related, maybe extend the variant? Just out of curiosity: What kind of property are you trying to store, maybe we have some other ideas on that / hints on solutions.

**Comment by sunilkumarnagoore** [comment]
i need add property value like large urls and  rest api body

**Comment by flobby** [comment]
@sunilkumarnagoore did this solve your issue? If yes can you please close this issue :)

**Comment by sunilkumarnagoore** [comment]
@flobby  not solved yet
