### ISSUE TITLE
Shipments are not updated when Shipping Address Changes

### ISSUE THREAD

**Issue by flobby** [spree/spree#10276]
If a user changes his shipping address in checkout, the shipment keeps the old address. Also the shipping rates are not updated if the address changes.

Also: If the amount changes, price sacks might not be recalculated. (I'm investigating this and create a new ticket if that persists)

## Expected Behavior
When changing the shipping country (or tax zone) shipment should get updated since prices might change.

## Actual Behavior
Old address is used and shipments are not recalculated

## Possible Fix
Shipping Address change on order should also check if a new shipment needs to be generated / the shipment needs to be updated.

## Steps to Reproduce
I'm using API v2, but I also can reproduce this in admin.

**API V2**
1. Create cart, add product, ...
2. Checkout: Set Shipping Address
3. Request shipping rates
4. Change shipping address
5. Request shipping rates again
Result: Shipping rates should be the same. In Database you should also see, that the ID is the old one (from request 2)

**Backend**
1. Go to order that is not complete
2. Check shipping rate
3. change country for shipment and save
4. check shipping rate again

Of course you need to setup different shipping rates for those countries to see the effect.

## Your Environment
* Version used: Latest spree from master

**Comment by johannboutet** [comment]
I'm faced with the same issue in API v2, changing the shipping address doesn't put the order back in the `address` state, and doesn't refresh the shipping rates.

As I understand it, in the "classic" frontend, the controller `Spree::CheckoutController` has a `before_action :set_state_if_present`, which sets the state of the order to the value of the route param, so then when the `update` method is called, the state of the order is changed. So updating the address by POSTing to `/checkout/update/address` automatically puts the order back in `address`, then `next` is called on the order, which triggers the `before_transition to: :delivery, do: :create_proposed_shipments`, which refreshes the shipping rates...

Since the API v2 has no such mechanism to automatically recalculate the order state, I see two possible solutions:

1. add `:state` to the `permitted_checkout_attributes` and leave the responsibility to the user of the API to set the order state accordingly when making changes
2. the `Spree::Checkout::Update` service already has some special logic if the params contain an address (see `address_with_country_iso_present?`), we could detect if the shipping address has been changed and change the state of the order to `address` there

Solution 1 is probably not a good idea since that would require a lot of validation both on the API side and the client side. Solution 2 is probably the best choice.

**Comment by fauno** [comment]
Hi, is the patch going to be backported to 4.1?

**Comment by damianlegawiec** [comment]
> Hi, is the patch going to be backported to 4.1?

Yes, we'll release 4.1.10 containing this fix tomorrow 😀
