### ISSUE TITLE
Internal Server Error on promotion code removal, when a cart item is added with the promotion

### ISSUE THREAD

**Issue by jjo-fs** [spree/spree#10560]
## Context
If one creates a promotion that adds an item to the cart when entering the promotion code, one would also like to be able to remove that promotion afterwards if it is not wanted. Currently when trying to remove the promotion code, an internal Server Error is returned.

## Expected Behavior
The added item and the promotion code should be removed.

## Actual Behavior
Internal Server Error.

## Possible Fix
The error lies within spree_core,  ```app/model/spree/promotion_handler/coupon.rb``` line 79, which should be:
```Spree::Dependencies.cart_remove_item_service.constantize.call(order: order, variant: item.variant, quantity: item.quantity)```
Instead of:
```Spree::Dependencies.cart_remove_item_service(order: order, item: item.variant, quantity: item.quantity)```

## Steps to Reproduce
1. Create a promotion which adds an item to the customers cart
2. Enter that promotion code in the cart
3. Try to remove that promotion code

## Your Environment
* Version used: spree_core-4.1.11
* Ruby: 2.7.2, Rails: 6.0.3.4

**Comment by piotrpanko** [comment]
@jjo-fs 
The issue itself is present but i didn't experienced any internal server errors. I added an item via promotion and few things happened:
- There's no way to remove this promotion - no buttons and such
- When i try to remove the item, it will be added again due to the promotion

Because of that i'd like to clarify few things:
- Did you you use "Create line item" action in promotion?
- In what ways did you try to remove the promotion? By removing the item or via console?
