### ISSUE TITLE
Any plan to add icon for print(printer)?

### ISSUE THREAD

**Issue by poudelprakash** [spree/spree#10583]
**Is your feature request related to a problem? Please describe.**
I could not find any icon suitable for print option for backend.

**Describe the solution you'd like**
a printer icon would be awesome addition

**Comment by MatthewKennedy** [comment]
Hi @poudelprakash 

If you are looking to use custom svg icons in the admin when creating a Spree extension, you can create a custom icon: `backend-printer.svg` place this in the `app/assets/images` folder manually, or write a line in the install generator to copy the asset across from your extension, and then point to the image by dropping the `backend-` in the view

**Example**
`<%= tab Spree.t(:'admin.tab.print'), url: spree.admin_print_path, icon: 'printer.svg' %>`

If you are writing an extension you can write a Spree config that uses the old glyph-icons by default, and allows users to customise the icon via a config setting a string.

`    <%= tab Spree.t(:'admin.tab.blog_posts'), url: spree.admin_posts_path, icon: Spree::Config[:blogs_custom_icon] %>
`

**Comment by poudelprakash** [comment]
@MatthewKennedy Thank your for this awesome step wise explanation of how this can be achieved.

I was still thinking if print icon should be included in core app itself as it will have more common use case (eg: print shipping label)

**Comment by MatthewKennedy** [comment]
@poudelprakash Not a problem at all, I hope it helps, I see your point it would be a common used icon in an e-commerce store, and if its missing from an existing button in the default Spree Admin UI then it will mot likely need adding.

My personal feeling is that, I don't think it is a good idea to add any more icons than those absolutely required in the stock Admin UI by default.

The reason is, if Spree users are encouraged to use their own custom svg icons when customising their Spree project, and also use custom svg icons for Spree extensions they are creating as outlined above, then the maintainers of Spree can worry less about managing a large set of icon assets.

An example of where this becomes an issue is when icons are seemingly unused by default in the Admin UI, but somewhere down the line icons were added here and there to fit anticipated use cases, and in 3 year time Spree has 200+ admin UI icons, and the maintainers of Spree can't delete a single icon, because peoples Spree extensions might be relying on them, and they are now not only maintainers of a Rails based e-commerce store but also the maintainers of a large svg icon pack.
