### ISSUE TITLE
uniqueness: { allow_blank: true } is not valid in Product

### ISSUE THREAD

**Issue by mrbrdo** [spree/spree#11685]
https://github.com/spree/spree/commit/3bb6d80bb72d42777ab5d8bbbe2839e8643f855c

I don't think `uniqueness: { allow_blank: true }` is valid, and also would still make no sense together with `presence: true`

**Comment by vfonic** [comment]
Did you try running tests?
Can you provide a test case that makes this working/not-working?

I believe it's working fine.

c/p from my comment at https://github.com/spree/spree/commit/3bb6d80bb72d42777ab5d8bbbe2839e8643f855c:

Seems like `allow_blank` is indeed an option for `uniqueness`. I guess it means that it allows two or more records to have blank `slug` without considering them to fail the uniqueness validation.
`presence: true` together with `allow_blank: true`, sounds unintuitive. But seems like what it does is it makes sure that only one validation error is shown when validation fails. So it shows "slug can't be blank" or "slug has already been taken". It does some other things and allows some blank values, but prevents other "empty" values.
https://newbedev.com/understanding-rails-validation-what-does-allow-blank-do

I've got a question for you:
What's the point of your comment directly on this commit? Can you please open an issue instead or open a PR fixing this issue if there is any issue?
Otherwise, it seems like it might waste both mine and your time and will end up nowhere.

It would also help to try and change the tone of your comment if you're expecting a reply: "what the hell?" as the only comment, even on a buggy code, is not the way to go.

**Comment by mrbrdo** [comment]
Sorry, you're right. I forgot why I was having an issue with this, so I will close it.

**Comment by vfonic** [comment]
You're definitely right, the code looks "off". Perhaps adding a comment above this line of code would help people in the future to understand how this works?
I'm no longer involved with the project so feel free to open a PR if you think it would help.

Thanks! 🙏

**Comment by mrbrdo** [comment]
@vfonic thanks for your clarification!
