### ISSUE TITLE
undefined method `to_url` for nil:NilClass when creating taxonomy

### ISSUE THREAD

**Issue by mbajur** [spree/spree#11899]
My spree instance is throwing `undefined method 'to_url' for nil:NilClass`

## Context
It's happening when I'm trying to create a taxonomy either using admin panel or directly via console. Name of the taxonomy is being provided as expected.

## Actual Behavior
![image](https://github.com/spree/spree/assets/581569/e67bb134-763b-44c4-9bc8-9331ef727e2c)

## Steps to Reproduce
1. Create a store
2. Set it's default locale to PL
3. Set supported locales to EN and DE
4. Try to create a new taxonomy

## Your Environment

* Version used: 4.6.0
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/mbajur/511555171fefc967bb67144051a2166a

**Comment by stap780** [comment]
Hello
also have the same issue with two different install. One starter and one that do myself.
Anybody have a solution?

**Comment by rafalcymerys** [comment]
I did some investigation on this one - it seems that when store.default_locale is different from I18n.default_locale, Mobility's fallbacks return a `nil` for the name (instead of the name that was set when creating the taxonomy).

I'll dig a bit deeper into it, as this seems to be an edge case for translation fallbacks in general. I think creating a Taxonomy is the only place where it really surfaces, but it would be great for the fallbacks to work consistently across the board.

**Comment by rafalcymerys** [comment]
@mbajur I've just pushed a fix with Spree 4.6.1. Please take a look and let me know if that works fine for you now.

**Comment by mbajur** [comment]
I can confirm it indeed fixed it. Thank you! 🙌
