### ISSUE TITLE
Spree::Auth::Config[:confirmable] cannot be configured

### ISSUE THREAD

**Issue by aforty** [spree/spree#11933]
I was told by Rafal Cymerys to file this issue.

It seems like storing `Spree::Auth::Config[:confirmable]` in the database doesn't make sense since it doesn't allow the value to be changed at runtime.

> Anyone know where I should be setting `Spree::Auth::Config[:confirmable]`? If I set it in an initializer I get this
> ```
> uninitialized constant Spree::Preference (NameError)
>       @persistence && Spree::Preference.table_exists?
> ```
> if I set it in `Rails.application.config.after_initialize` it’s too late and `Spree::User` has already been loaded with confirmable ([here](https://github.com/spree/spree_auth_devise/blob/b048a33b0771130f4c0cdf503dc2eb5125107e91/app/models/spree/user.rb#L12))

**Comment by rafalcymerys** [comment]
Hi @aforty thank you! I've created a PR with a potential fix here: https://github.com/spree/spree_auth_devise/pull/582/files
I tested this locally so far and seems to be working fine. It would be great if you could try using this branch - I would appreciate your feedback as well.

There are still a few tests that fail on that branch - they seem to be caused by the way these tests unload constant for test purposes. I will try to resolve these soon.

**Comment by rafalcymerys** [comment]
Thank you. I will create a new release of spree_auth_devise today/tomorrow.

**Comment by aforty** [comment]
Fantastic, thank you!

**Comment by rafalcymerys** [comment]
@aforty FYI I've just published spree_auth_devise 4.6.0
