### ISSUE TITLE
Calculator fails to load after loading sample data

### ISSUE THREAD

**Issue by nigelr** [spree/spree#4522]
While an app is running, if you reset/reload db & samples using:-
rake db:drop db:create db:migrate db:seed AUTO_ACCEPT=1 && rake spree_sample:load --trace
after login in again the calculator field does not show any options
![screen shot 2014-04-01 at 6 18 56 pm](https://cloud.githubusercontent.com/assets/14952/2576876/acf6f8f8-b976-11e3-9e25-269bb88141e0.png)

After restarting server and a page reload the calculator will work again

**Comment by RaVbaker** [comment]
I also came across this issue. Specially in development environment when spring active. But I found a quick fix solution for it. Tell me guys what do you think. I know it's a bit hacky but it does the job. Instead of line https://github.com/spree/spree/blob/master/core/app/models/spree/shipping_method.rb#L42:

        def self.calculators
          spree_calculators.send(model_name_without_spree_namespace).select{ |c| c < Spree::ShippingCalculator }
        end

we might use:

        def self.calculators
          spree_calculators.send(model_name_without_spree_namespace).select{ |c| c.to_s.constantize < Spree::ShippingCalculator }
        end

It forces ruby to use latest available instance of class object.

**Comment by arthurtalkgoal** [comment]
Hi @RaVbaker,

I have the same issues, I wonder if there is any update for the issue since it's last yr issue.

I will use your soln at this moment. Thanks.

**Comment by RaVbaker** [comment]
@JDutil I can prepare a PR with this change if you accept they way I described above of doing it.

**Comment by JDutil** [comment]
@RaVbaker that would be good thanks
