### ISSUE TITLE
Address not loaded if order transitioned to my user after logging in.

### ISSUE THREAD

**Issue by tesserakt** [spree/spree#5255]
Steps to reproduce
1) Log out.
2) Add something to the cart
3) Click checkout
4) Login
5) Get directed to the address page with none of your default address info filled in. 

I managed to fix this by calling this in the checkout_controller
```
  def edit
    @order.assign_default_addresses! if (@order.ship_address.nil? && @order.bill_address.nil?)
  end
```

but it is not ideal. Thoughts? Perhaps we could put this in?

```
after_transition to: :address, do: :assign_default_addresses!

```

**Comment by mvz** [comment]
I'm seeing something similar with Spree 3.0, which already contains

```
before_transition to: :address, do: :assign_default_addresses!
```

I've noticed that going to `/checkout/address`, the order does not transition to the `address` state, hence this action is not triggered.

**Comment by mvz** [comment]
The problem in the previous comment is different from @tesserakt's original problem and was caused by the old spree_minicart plugin.

Also, I can confirm @tesserakt's problem. I believe it is caused by the fact the the order is already in the address state during the registration step. This is why adding a hook to the transition to address does not work.

**Comment by aishmita-aggarwal** [comment]
Unable to replicate this.

**Comment by priyank-gupta** [comment]
Not able to replicate.
