### ISSUE TITLE
Undefined method `name` for nil:Nilclass in stock movements

### ISSUE THREAD

**Issue by coorasse** [spree/spree#5355]
The list of movements for a stock location throws an exception if one of the variants associated with a stock movement has been deleted.
The problem is in stock_movements controller index action:
`@stock_movements = stock_location.stock_movements.recent.includes(:stock_item => { :variant => :product }).page(params[:page])`

the variants are loaded with their default_scope (screw it) by acts_as_paranoid and so, if it has been removed, it is null.
If you remove the `includes` everything works just fine, since it access the variant through stock_item.variant.

**Comment by felipekk** [comment]
I ran into this problem as well. Using only <tt>includes(:stock_item => :variant)</tt> still returns items with <tt>variant = nil</tt>. Removing the includes though means running 2 SQL Queries for each stock_movement (one query for stock_item, one for variant).

**Comment by lelelelemon** [comment]
Hi, 

Is this issue solved? I reproduced the problem by delete a variant on purpose through rails console. 
by 
```
variant = Spree::Variant.first
variant.delete
```
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/6993863/50946942-865aed80-1461-11e9-9116-e41012a151c4.png">

I am curious in which situation will a variant be deleted instead of destroyed(its associated stock_items will be deleted too you can find it in VariantsController destroy action).  @coorasse @felipekk

We are a research team from University of Chicago, and we want to dig into bugs like this to get a better understand. 

We appreciate that if you can give some detailed feedback.
