### ISSUE TITLE
Free shipping promotion doesn't work on cart but works on checkout ?

### ISSUE THREAD

**Issue by nimashariatian** [spree/spree#5420]
Not sure if this is a bug or a default behaviour 

Steps to reproduce: 
1. Create a promotion with the following: 
- add action type: free shipping
- set a starts at date

2. Add an item to the cart.
- attempt to apply the code, you get:  "This coupon code could not be applied to the cart at this time."

3. Apply the same coupon at the checkout and everything works?

![create_free](https://cloud.githubusercontent.com/assets/210358/4423141/531dc142-4592-11e4-9e7f-16c9a7fb0ef4.png)

![error_free](https://cloud.githubusercontent.com/assets/210358/4423146/595facf0-4592-11e4-9c4c-da64f578825e.png)

**Comment by JDutil** [comment]
Currently with how the coupon code promotion handler works it checks in the code is valid, and also attempts to apply the promotion to the order.  Since the shipments do not exist we're unable to apply the shipment promotions.  This is actually the expected behavior, and we haven't come up with a good way to allow this to work.  Since we also find it confusing to have the promo code code field on the cart page, and the payment page behaving differently we've decided to remove the promo code field from the cart page altogether in Spree 3.
