### ISSUE TITLE
Address auto-complete in Chrome completing up to country

### ISSUE THREAD

**Issue by lukemorton** [spree/spree#5480]
When using Chrome's autocompletion tool only the fields up to and including country are populated. The zip code and phone number are left empty. I can then use autocomplete on the zipcode field and it completes that and phone number.

Anyone got an idea whats doing this?

**Comment by pawelnguyen** [comment]
well, I checked it out and it seems that the problem is with `<noscript>` tags:
https://github.com/spree/spree/blob/master/frontend/app/views/spree/address/_form.html.erb#L56-L58

It looks like chrome stops autofilling fields the moment it encounters `<noscript>`. I think it's a chrome bug but I didn't find any report of it.

I'll try to investigate it further but I don't see any workaround/fix for now

**Comment by pawelnguyen** [comment]
I submitted an [issue](https://code.google.com/p/chromium/issues/detail?id=448767&thanks=448767&ts=1421246674) to chromium
that's really weird, it looks like only this particular setup of `div`, `p` and `input` elements produces this bug

Here's a [fiddle](http://jsfiddle.net/rnrt9765/8/) if someone want's to play with it

**Comment by JDutil** [comment]
Thanks for tracking down why it's happening this was an issue bugging me.

**Comment by pawelnguyen** [comment]
:) from our side we can try restructuring html of the form a bit, but I don't know if it's worth fixing autofill in one browser

**Comment by madmath** [comment]
As mentioned on the Chromium issue, it's possible that this would be solved using "autocomplete" attributes on all the fields.

For a good implementation of that, see a typical shopify checkout page, or squarespace.

Let me know if you have any questions!

**Comment by nishant-cyro** [comment]
@priyank-gupta @Mafi88 @damianlegawiec - This one works fine for me :)

**Comment by Mafi88** [comment]
@priyank-gupta @damianlegawiec @nishant-cyro Works for me too. Probably the Chromium was patched :)
