### ISSUE TITLE
Returns in 2.4 stable are not functioning properly.

### ISSUE THREAD

**Issue by niedfelj** [spree/spree#5982]
There is clearly a bunch of messed up logic with the new "returns/authorizations" code.  If you go into "Customer Returns" for a shipped order and return an item that doesn't have a matching RMA, it creates a "rejected" return with the error {:rma_required=>"Return item requires an RMA"}.  However, it marks the order returned, it shows no credit_owed, and then the item is actually RETURNED and marked returned (and the rejected return actually says 'reimbursed').  This puts the whole order in a state that can't be fixed, because you can no longer create an RMA (it has no checkbox to select the item and then says "no shipped units" on submit).  Screenshots attached below.  

I'm sorry to say, I no longer trust Spree releases and have forked the code over where we will maintain our own version.  It has turned into a huge mess of unreliable and hacked code.  We are actually trying to run a store on it, and every release breaks multiple parts of our business.

![screenshot 2015-01-30 14 56 13](https://cloud.githubusercontent.com/assets/294487/5982468/45f0bb34-a891-11e4-8e8c-56f3141f42a8.png)
![screenshot 2015-01-30 14 55 15](https://cloud.githubusercontent.com/assets/294487/5982469/45fd58da-a891-11e4-8bea-9e7d0f7be240.png)
![screenshot 2015-01-30 14 47 07](https://cloud.githubusercontent.com/assets/294487/5982470/45ffb468-a891-11e4-8cfa-9776ed146465.png)
![screenshot 2015-01-30 14 46 29](https://cloud.githubusercontent.com/assets/294487/5982472/45ffd376-a891-11e4-9364-c711603ea772.png)
![screenshot 2015-01-30 14 46 16](https://cloud.githubusercontent.com/assets/294487/5982471/45ffcdc2-a891-11e4-8598-2bb0311ad772.png)

**Comment by athal7** [comment]
That does seem frustrating, for what it is worth you can configure your return item eligibility rules in https://github.com/spree/spree/blob/master/core/app/models/spree/return_item/eligibility_validator/default.rb.

It seems some of your confusion is based on an unfamiliarity with the new returns system. What you have to understand about return items is that they have different statuses for whether they have been received back into inventory vs whether they have been refunded / reimbursed. In the case you are describing, they have physically been received back into inventory, this is why the order is marked as returned, but they have not been deemed acceptable to receive back into inventory due to the eligibility rules described above. 

In the case where you have eligibility rules that are not setup optimally for you and you get into a frustrating situation, you can always create a 'refund' in the payments section of order admin. This is not ideal because it's not directly tied to the customer return, but will allow you to service your customer til you get things tweaked.

Lastly I have to say that, while I do not work at Spree and I have my own frustrations with the pieces of the codebase and process, there are many people who work hard to maintain this project and take it in a positive direction, and a a little human courtesy would be appreciated. I've noticed that you took a similar tone on issues filed in spree-contrib/legacy_return_authorizations over the last couple of days, and I have tried my best to be kind in spite of your rudeness. I hope that you can find a more productive way to communicate on this project, else you will most likely not find me (and others) so amenable to helping you in the future. MINSWAN

**Comment by niedfelj** [comment]
I don't think directness should be confused with rudeness.  There is a code quality problem with this project, which I think others should be aware of.  When a release comes out with a major new feature that just plain doesn't work, along with documentation that is wrong, and a separate "extension" for "legacy" stuff that doesn't work, then yes, I think it should be pointed out so that the many people who maintain this project can step back and decide how they want to fix their team structure and development/release workflow.  I understand that bugs are inevitable, and I contribute to a lot of different open source projects.  The issues cropping up with Spree are not bugs, but general lack of oversight/quality control.

**Comment by JDutil** [comment]
@niedfelj we're well aware of the quality control issues, and are working to improve our processes.  There are plenty of large stores using the new returns system without a hitch, and we can't fix any issues that do arise with it until we know they exist so it would be nice to have a community that tests and reports bugs back to the project rather than fork it and do their own thing.  You're more than welcome to do that though that's the beauty of open source, but you should consider a lot of people put a lot of hard work into getting Spree to where it is today and your welcome for not having to write your own store from scratch.  As for having to do legacy breaks in the codebase that is going to be inevitable at this point because as you say there are lots of parts of Spree that plain stink that were hacked together years ago.  We're trying to rebuild the foundation of Spree with the lessons we've learned over the years in order to resolve most of these code quality issues, and making smoother upgrade paths going forward.  Unfortunately that means we're going to have to break things though unless you want us to continue onwards with hacked together code that's evolved over 6 years inevitably leaving legacy code we need to lose.

**Comment by crystalized** [comment]
Dunno why this isn't fixed in the main code since it seems like something really simple to fix.

I used a customer return decorator to fix it.

    Spree::CustomerReturn.class_eval do
	validate :must_have_return_authorization, on: :create

    private
        def must_have_return_authorization
   	    if return_authorizations.none?
     	        errors.add(:base, "has no Return Authorization")
   	    end
       end
    end

**Comment by JDutil** [comment]
Please submit a pull request. That is how open source software is improved. closing this as a stalled issue
