### ISSUE TITLE
How to add user concerns 

### ISSUE THREAD

**Issue by funkdified** [spree/spree#6007]
I am adding spree to an existing devise app and ran into this problem: https://github.com/spree/spree/issues/5393

I was able to fix the issue with orders by adding `has_many :orders, class_name: 'Spree::Order'` to my User model, but I'm wondering what else might be missing. What else is necessary to avoid all future User related errors?

Thanks

**Comment by JDutil** [comment]
These are the concerns spree_auth_devise uses:
https://github.com/spree/spree_auth_devise/blob/master/app/models/spree/user.rb#L3-L4

There is also this user extension that should be being applied for you as well:
https://github.com/spree/spree/blob/master/core/config/initializers/user_class_extensions.rb

It looks like the error you ran into is because this association should just be orders not spree_orders:
https://github.com/spree/spree/blob/master/core/config/initializers/user_class_extensions.rb#L13

**Comment by funkdified** [comment]
Thanks very much for answering so quickly @JDutil ... One last question. 

I have added the following to my User model:

```
  include Spree::UserAddress
  include Spree::UserPaymentSource
  
  include Spree::UserApiAuthentication
  include Spree::UserReporting

  has_and_belongs_to_many :spree_roles,
                          join_table: 'spree_roles_users',
                          foreign_key: "user_id",
                          class_name: "Spree::Role"

  has_many :orders, foreign_key: :user_id, class_name: "Spree::Order"

  belongs_to :ship_address, class_name: 'Spree::Address'
  belongs_to :bill_address, class_name: 'Spree::Address'

  # has_spree_role? simply needs to return true or false whether a user has a role or not.
  def has_spree_role?(role_in_question)
    spree_roles.where(name: role_in_question.to_s).any?
  end

  def last_incomplete_spree_order
    orders.incomplete.order('created_at DESC').first
  end
```

When launching the rails server I see the following warning messages:
```
/home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: already initialized constant User::HABTM_SpreeRoles
/home/funkdified/.rvm/gems/ruby-2.1.2@rails4.1/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: previous definition of HABTM_SpreeRoles was here
```

**Comment by funkdified** [comment]
Also just found this issue as well:
```
ActiveModel::MissingAttributeError - can't write unknown attribute `bill_address_id':
```

**Comment by JDutil** [comment]
This https://github.com/spree/spree/blob/master/core/config/initializers/user_class_extensions.rb is being evaluated on every instance initializing so you're duplicating code in your user class.  

Since the bill and ship address associations are being added you'll need to add bill_address_id and ship_address_id columns to your user table.  We should either document that if it's not already, which I'm assuming it's not if your running into it.  Were you following a guide, and would you want to update it?
