### ISSUE TITLE
Payment state and shipping state selects are missing in admin orders index view.

### ISSUE THREAD

**Issue by tvdeyen** [spree/spree#6143]
They are only text fields at the moment: https://github.com/spree/spree/blob/3-0-stable/backend/app/views/spree/admin/orders/index.html.erb#L57-L69

Shouldn't this be select tags with valid payment and shipping states?

We found https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L73-L77 as a suitable candiate for the shipment state select.

And with the same pattern we could extract all payment states from https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L73-L77

We could provide a PR, if this is the right solution.

:beer:

**Comment by JDutil** [comment]
Yes those would be much nicer as select fields if you could submit a PR

**Comment by tvdeyen** [comment]
@JDutil I ran into an issue while testing the feature. Maybe you can help me understand payment and shipment states.

For the order state select you use all available states from the `Order.state_machine`.

If I use the `Shipment` and `Payment` state machines respectively I get different values:

#### Available payment states in the translations:

- balance_due
- checkout
- completed
- credit_owed
- failed
- paid
- pending
- processing
- void

#### Payment states returned by the state machine:

- checkout
- pending
- completed
- processing
- failed
- void
- invalid

#### Available shipment states in the translations:

- backorder
- canceled
- partial
- pending
- ready
- shipped

#### Shipment states returned by the state machine:

- pending
- ready
- canceled
- shipped

What are the expected states I should use in the select tag for the filter? And where do I get them from?

Any help is very much appreciated. Thanks in advance :tulip:

**Comment by JDutil** [comment]
Hmm interesting point.  So the issue here is that these payment and shipment states are for the Order itself not for the respective payment/shipment object.  So the payment/shipment state machines don't need to be concerned with if there are multiple payments or shipments while the order does.  We determine that states here: https://github.com/spree/spree/blob/master/core/app/models/spree/order_updater.rb#L117-L172 so I suppose we would just want to use each of these possible states.  Perhaps we can extract the possible states into a constant or enum that we can use for the select options and assignment in the updater.

**Comment by tvdeyen** [comment]
A constant is what I already thought of.
