### ISSUE TITLE
taxons_tree helper takes too long with many taxons

### ISSUE THREAD

**Issue by parndt** [spree/spree#6158]
With over 55,000 taxons the default home/index.html.erb takes over 50 seconds to render because of a recursive method, `taxon_tree`.  This is on version 2.4.5 but is probably the same on version 3.0.0

```
Rendered spree_frontend-2.4.5/app/views/spree/shared/_taxonomies.html.erb (52821.8ms)
```

I don't have a solution right now, but I wanted to report the issue.

**Comment by radar** [comment]
Hello. Long time no speak.

I helped @parndt debug this issue.

The `taxons_tree` method is definitely to blame here, mainly the part where it does this:

```ruby
root_taxon.children.map do |taxon|
```

If the root taxon has a large number of children, this `map` will attempt to render a link for each of these. In @parndt's case, the numbers of these children for the root taxons were 19, 4,795, 2, and 50,877.

I think the fix for this issue may be as simple as limiting the children iterated over in `taxons_tree` to a number -- let's pick 20 because it's a nice number.

So the code would look like this:

```ruby
root_taxon.children.limit(20).map do |taxon|
```

(or similar, I haven't tested this)

I defer this to your good tastes.

**Comment by radar** [comment]
Oh and you'd probably want to limit the `children` association on the `Taxon` model too.

**Comment by JDutil** [comment]
That's a lot of taxons...  will see what we can do about `taxon_tree`.

**Comment by parndt** [comment]
Similar issue with variants [here](https://github.com/spree/spree/blob/2-4-stable/backend/app/views/spree/admin/orders/index.html.erb#L56) except this takes even longer :smile:

**Comment by JDutil** [comment]
Does https://github.com/spree/spree/commit/2efbd7dbf3f0e3b0d3b1c940ca6350eef99fe496 go far enough in performance gains for you here?

**Comment by parndt** [comment]
No, the improvement from that is relatively small

**Comment by parndt** [comment]
Closed because won't fix?

**Comment by bbonislawski** [comment]
@parndt we're going to rebuild API and frontend part during year 2018. We cannot focus on fixing legacy stuff and need some way of going further with API v2 and new frontend
