### ISSUE TITLE
Package weight set to zero when Product and LineItem have weight

### ISSUE THREAD

**Issue by brchristian** [spree/spree#6275]
In the latest `2-3-master`, if I open a Rails console, I can produce the following unexpected behavior:

```ruby
product = Spree::Product.new(weight: 5)
line_item = Spree::LineItem.new(product: product, quantity: 1)
stock_location = Spree::StockLocation.new
order = Spree::Order.new
package = Spree::Stock::Package.new(stock_location, order)
package.add(line_item, 1)
```

Here's where things appear to get strange:

```ruby
product.weight.to_s
=> "5.0"
product.master.weight.to_s
=> "5.0"

package.weight.to_s
=> "0.0"
package.contents[0].variant.weight.to_s
=> "0.0"
```

Am I missing something here? I am expecting `package.contents[0].variant.weight` to equal `product.master.weight` . . .

**Comment by JDutil** [comment]
This:
https://github.com/spree/spree/blob/master/core/app/models/spree/stock/package.rb#L33

Should sum variant.weight * quantity:
https://github.com/spree/spree/blob/master/core/app/models/spree/stock/package.rb#L33

So yea that does appear to be incorrect not sure why though.  My guess would be that since you haven't saved the product it's master variant isn't created yet.

**Comment by brchristian** [comment]
@JDutil My hunch was also that it was coming from the fact that these records not having been persisted to the db yet. Is this worth looking into, or is it simply not designed to need to work in these cases?

**Comment by JDutil** [comment]
It should work if the variant exists, which it appears to exist if you can reference the association.  I have the feeling there is something funky going on with how rails is handling the association, and the record may need to be persisted for it to work properly I'm not sure.
