### ISSUE TITLE
Cached product page not invalidated if new taxons added to product

### ISSUE THREAD

**Issue by greinacker** [spree/spree#6320]
Steps to repro:

First, ensure the cache is enabled - i.e. run on production, or enable cache in development. Then...
1. Create product, add one or more taxons to it.
2. View product on front end, which will cache the product page. The product's taxons are listed in the "Similar items" section of the product page.
3. In admin site, add an additional taxon to product
4. View product on front end again - the new taxon is not shown under "Similar items"

It's definitely a caching issue - if you clear cache, then view the product in the front end again, you'll see the updated taxons.

This is happening because when adding a taxon, the product itself doesn't get updated...thus this line in app/views/spree/products/show.html.erb:

```
<% cache [I18n.locale, current_currency, @product] do %>
[...]
```

does not change the cache key, and thus never invalidates.

**Comment by greinacker** [comment]
Thanks for the quick fix, @JDutil.  FYI, this fixes the specific use case I described, but there is still a scenario where the cache doesn't get busted - that's if you have a set of taxons assigned to the product, and you remove one of them from the product. In that case, the product isn't touched, and the cached page (now out of date) is still shown.

**Comment by JDutil** [comment]
Hmm yea good point.  Probably need a before_destroy filter on classification to touch the product then as well.

**Comment by JDutil** [comment]
Well apparently destroy callbacks not working.

**Comment by JDutil** [comment]
@greinacker you could try changing:
https://github.com/spree/spree/blob/master/core/app/models/spree/product.rb#L34

To something like:
```
has_many :taxons, through: :classifications, after_remove: -> { @nested_changes = true }
```

I'm not sure if that runs before or after the save though ideally it would run before so that #anything_changed? returns true, and touch callback runs:
https://github.com/spree/spree/blob/master/core/app/models/spree/product.rb#L81

Would suck if it doesn't run until after as that would require additional database queries from running touch callbacks twice like:
```
has_many :taxons, through: :classifications, after_remove: :run_touch_callbacks
```

Let me know whichever works ideally without the extra touches.

**Comment by ducnguyenhuy** [comment]
I got similar this in production env.

For now, when admin update TAXONS for a product, I don't see that change on front page except admin go to CONFIGURATION -> general_settings -> click "Clear Cache".

Any suggest how to fix this?

Thanks much.
