### ISSUE TITLE
VAT with promotions calculated wrongly

### ISSUE THREAD

**Issue by vrosancic** [spree/spree#6475]
Hello,

Say that I have variant with price 6000 (including VAT). I have a promotion with 50% discount. Tax rate is 25%. When I add variant in cart, total tax rate is 1200 (which is wrong, it should be 600), but when I add another (quantity is now 2), total tax rate is 1800 (1200 + 600). It seems that tax rate is calculated wrongly first time and correctly second time which is strange.

I think the problem is in TaxRate.store_pre_tax_amount method where item.promo_total for the first time is 0, and for the second time is 3000 (it should be 3000 first and 6000 second time).

Do you know what is happening?

**Comment by vrosancic** [comment]
I think the solution is to add this line:
Spree::TaxRate.adjust(order, [line_item])
to the Spree::OrderContents class, in method after_add_or_remove, after the line: Spree::Adjustable::AdjustmentsUpdater.update(line_item).

It works for me now. Please verify this and I will add it to pull request.

**Comment by mamhoff** [comment]
I can verify this happening, and will look into it sometime next week. I think it's got to do with when exactly the promotion adjustment is added, and what object then gets passed into `TaxRate`.

**Comment by vrosancic** [comment]
I have done this:
In Spree::OrderContents class, method after_add_or_remove, I added this line: Spree::TaxRate.adjust(order, [line_item]) 
right after this: 
Spree::Adjustable::AdjustmentsUpdater.update(line_item)

Also in Spree::LineItem class, in method update_adjustments, I changed order of recalculate methods and removed if quantity changed check so adjustments and taxes are recalculated on every save. My update_adjustments method looks like this:

def update_adjustments
  recalculate_adjustments
  update_tax_charge 
end

I think it works now like it should, but I don't know how this affects other things in spree like additional taxes. Could you check if this is ok?

**Comment by mamhoff** [comment]
It looks to me like either of these changes could do the trick. Well done! 

It'd be really great if you could supply a Pull Request. If you have not done that before, I'm happy to help out. Here's a starter: https://help.github.com/articles/using-pull-requests/. There's also Spree-specific instructions here: https://guides.spreecommerce.com/developer/contributing.html#creating-a-pull-request. 

Spree has a very comprehensive Test Suite, so that the probability of things breaking without anyone noticing is quite small. Ideally, you'd also write a test for your case. In my experience, that is the hardest thing to do, especially when you're dealing with many different models at the same time (as in this case). If your PR does not include tests, I can jump in and help you out with those next week. 

Basically, what you'd have to do is the following: 

1. Fork Spree into your Github account

2. Clone that copy of Spree onto your computer using this command: 

` bash
git clone <your spree repo url>
cd spree/core
bundle 
rake test_app
`

This will make a copy of Spree that's ready for contributing on your machine. 

Make your changes in this repo, then run 

`rspec`

This will take a while (~10-15 Minutes on my machine). It runs all of the core tests for Spree. If none fails, you can commit your changes: 

`
git co -b fix-vat-for-percent-promotions
git add --all .
git commit -m "Fix VAT calculation with percent discounts"
` 

Like I said: Ideally you'd also provide some test code; there's lots of tests in the Spree repo to learn from. 

After you're done coding and committing, run

` 
git push origin fix-vat-for-percent-promotions
`

If you now visit your repository (https://www.github.com/vrosancic/spree), Github will have noticed you did something cool and ask you whether you want to "compare branches and create pull request". Do that. :cake:

**Comment by vrosancic** [comment]
Ok, I will do a pull request today or tomorrow.

**Comment by vrosancic** [comment]
I made a pull request #6542

**Comment by mamhoff** [comment]
Great work! :100:
