### ISSUE TITLE
Uncaught TypeError: obj.hasClass is not a function

### ISSUE THREAD

**Issue by Ionut-Milas** [spree/spree#6485]
I've removed all the Taxons and taxonomies and attempted to create new ones (children to taxonomies).
The "tree" does not appear.
I get this error: 
Uncaught TypeError: obj.hasClass is not a function
jquery.jstree.self-4133052a7f69ba15d0e4f85db43d4dc0ff19499b5fc5e512d704ce4b3e92f07b.js?body=1:671

I run Rails 4.2 and Spree latest

**Comment by victoryam** [comment]
I'm having the same problem :/

**Comment by danielstrimpel** [comment]
This is an old issue. Is it worth trying to reproduce or is it totally obsolete?

**Comment by lyminhtanh** [comment]
I've just get started with Spree these days and I've got the same problem like you guys.
I don't know exactly what happens with jstree code and spree translation but I've solved by this way:
1. gem uninstall --all (choose "Y" every time got prompt). Don't worry
2. bundle install
3. then I met an issue with ruby version, then run this to fixed: gem update bundler
4. rails db:migrate
That's it. Now I can create a new Taxonomy without any error when loading jstree
I don't know why this topic had been closed before. The issue is still there ...
It's should be better if we know the root cause anyway
