### ISSUE TITLE
Usage count for Promotions with per LineItem adjustments get calculated incorrectly

### ISSUE THREAD

**Issue by darbs** [spree/spree#6566]
Currently a per line item promotion usage is [limited](https://github.com/spree/spree/blob/715d4439f4f02a1d75b8adac74b77dd445b61908/core/app/models/spree/promotion.rb#L127-130) by the number of times its applied to each line_item. What this means is if a user applies the coupon code to their order and then adds more line_items those will not be affected by the adjustment. IMO since we allow only one promotion per order, that a per line item promotion usage count should be based on number of orders its applied to. I would be willing to open a pr if the community agrees. 

You can replicate this by creating a per line item promotion with a  limited usage. Apply it to an order, then add more line_items than the usage allowed for the promotion. I did this on 3-0-stable sandbox.

**Comment by nicedawg** [comment]
I, too, was surprised by this behavior.

Do you guys think it's a valid use case to say "this promo can only be used to create X line-item adjustments?"  I think most of the time, the store admin would rather say "this promo can only be used on X orders." 

I monkey-patched my 2-2-stable store to count Orders instead of Adjustments when determining Usage Count. I would be willing to open a PR as well, if the community agrees -- but should we make this a per-promotion option? Or a site-wide option? Or just change the behavior for all promotions?

**Comment by bbonislawski** [comment]
It depends on project. This is standard implementation and if you need, then you override it. I don't consider this as a bug so I'm closing
