### ISSUE TITLE
Understanding the Specs

### ISSUE THREAD

**Issue by alwinmark** [spree/spree#6663]
Hi,

I'm trying to understand the Specs to understand the implementation, so I took a look at:
https://github.com/spree/spree/blob/master/core/spec/models/spree/stock_transfer_spec.rb#L30

So when I understand everything correctly, the source_location and the destination_location are created by this Factory: https://github.com/spree/spree/blob/715d4439f4f02a1d75b8adac74b77dd445b61908/core/lib/spree/testing_support/factories/stock_location_factory.rb#L23 and so they have both 10 Items of variant 1.

So when I transfer 5 items from the source_location to the destination_location then I would say the correct assumptions should be:

```ruby
      expect(source_location.count_on_hand(variant)).to eq 5
      expect(destination_location.count_on_hand(variant)).to eq 15
```

But somehow its expected that both locations include 5 Products. Why?

**Comment by JDutil** [comment]
The source location creates 2 products with 10 and 20 qoh.

The destination location creates 2 products with 10 and 20 qoh, and stock items for the source location are also created with 0 qoh.

The spec is correct because each location has their own products with stock created, and then you transfer some of one locations stock to the other which does not have stock for that particular product it has stock of it's newly created products.

**Comment by alwinmark** [comment]
thanks here is the part ive overseen: https://github.com/spree/spree/blob/715d4439f4f02a1d75b8adac74b77dd445b61908/core/lib/spree/testing_support/factories/stock_location_factory.rb#L20-L21
