### ISSUE TITLE
Backend only Shipping Method not selectable

### ISSUE THREAD

**Issue by felipekk** [spree/spree#6693]
Steps to reproduce the problem:

1. Create a new spree store using spree 3.0.4, Rails 4.2.5, Ruby 2.1.5.
2. Login to backend, create a new Shipping Method "Store Pickup", Backend only, Default shipping category, USA Zone. 
3. Place a new order (frontend), selecting any shipping method.
4. Login to backend, try to change the shipping method of the new order to Store Pickup.

The list of available shipping methods should show Store Pickup as an option, it does not.

**Comment by felipekk** [comment]
This could be expected behaviour? Because if I add a new order manually through the backend I get the Store Pickup option. So it is not refreshing the list of available shipping methods if the order is "completed". Why?

**Comment by JDutil** [comment]
The shipping estimates are done during https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L493 and after the orders complete it's already done.  The options displayed when you try to change method are only the estimates that were already created.  I _think_ you might be able to work around this by just changing the qty of a line item, and then changing it back to the intended amount again so that the shipments are recreated.

**Comment by felipekk** [comment]
What if I just remove the condition <tt>order.completed?</tt> from the [controller](https://github.com/spree/spree/blob/master/backend/app/controllers/spree/admin/orders_controller.rb#L59)? This would theoretically regenerate the estimates but with my limited knowledge of the inner workings of spree I can't estimate side effects...

**Comment by JDutil** [comment]
:+1: didn't realize that was there.  Yea removing the completed check should be fine.

**Comment by nishant-cyro** [comment]
I am able to replicate this. Looking into it.
