### ISSUE TITLE
Validation failed: Sku has already been taken

### ISSUE THREAD

**Issue by ducnguyenhuy** [spree/spree#6789]
When I go to /admin/products and clone a product twice, I got an error about "Validation failed: Sku has already been taken"

Could you suggest me how to fix that error?

Thanks.

**Comment by JDutil** [comment]
Change the sku

**Comment by ducnguyenhuy** [comment]
Yes, I know but I saw you added validation for sku to model. So I think we should page with validation error message instead of showing a error page.

**Comment by JDutil** [comment]
So the server is returning 500 not just showing a flash message?  Please provide information requested in the contributing guidelines on filing issues https://github.com/spree/spree/blob/master/CONTRIBUTING.md#filing-an-issue in the future.

**Comment by simo163** [comment]
Hi @JDutil I haven't PRed yet in spree, could you please inform me how you normally discuss technical issues before making hands dirty or you just go implementing the solution you see it fits well?

Regarding this issue, I suggest for example, if the first clone of a product P1 creates a product P2 with sku "COPY OF P1", the second clone must give a product P3 with sku "COPY OF COPY OF P1".

Note: cloning P2 gives P4 "COPY OF COPY OF COPY OF P1".

What do you think?

Looking forward to contribute!

**Comment by jasonfb** [comment]
@simo163 please join the user group here: https://groups.google.com/forum/#!forum/spree-user

I will be happy to provide as much general assistance as I can.

personally I think adding "copy of..." to the duplicated object is a perfectly fine idea. However, your blocker is that the SKU can't be duplicated right? So would you also add "copy of..." to the SKU field as well?

The thing is, it feels like your problem is self-created, and easily correct with a human solution and not a technical one. Although adding "copy of..." to the names would eliminate the problem of getting blocked by the uniqueness validations, it seems to me that no real store would actually leave product names (or SKUs) with the name "copy of..."

It seems rather obvious to me that your workflow would be to copy the object, then *rename* the new object, giving it a new name and a new SKU. Assuming you do this, then you don't have a uniqueness problem on your second copy. 

So it seems to me that the flaw is in your Merchandiser/Operator's workflow, not in the code. Thus, I would classify your problem as an edge case. 

Nonetheless, I personally would support a PR that simply adds "copy of..." to the name & SKU during the copy process simply to eliminate the edge case.  There's no downside to that that I can see and it seems like it improves the overall experience for the Merchandiser/Operator.

**Comment by simo163** [comment]
Hi @jasonfb, 

I came with this solution actually only to avoid that the admin get into the error page when duplicating a product more than once without changing their SKUs previously.

I understand your approach, I just thought about it and  technically it seems logic. So in this case it would be nice to show an error alert that "The product cannot be cloned".

Moreover, I'd also go for adding "copy of.." solution, regarding to the advantages you explained in your last paragraph. What do you think?

**Comment by godalphul** [comment]
Would it be better to append a timestamp or random string to cloned SKUs? "copy of.." approach will still raise an error if the user forgets to change the cloned SKU or wants to change it later (ie fill out products and go back and enter real skus later). Is there any reason we'd want to force users to update the cloned SKU before making another clone?
