### ISSUE TITLE
Some times s3 bucket for amazon does not work

### ISSUE THREAD

**Issue by krazedkrish** [spree/spree#6892]
I follows the setups in https://guides.spreecommerce.com/developer/s3_storage.html. But, some times the images hosted in s3 is not available.
adding
    s3_host_name: 's3-us-west-2.amazonaws.com',
 
just below 
Spree.config do |config|
  attachment_config = {
    s3_credentials: {... },

helps, is it the permant solution, or is there a better one?

Thanks in advance.

**Comment by fabiode** [comment]
I did not used the recommended config because **Spree::Taxon** icon would still use local storage, if you're running in cloud setup prepared with scaling and load balancers, this is not a good idea.
Instead I had to create decorators overwritting params that _has_attachment_ has in each model, removing the _:rails_root/public_ in _path_ key and removing _url_ key from params and using:
```ruby
Paperclip.default_options.merge! {
    :storage => :s3,
    :s3_credentials => {
      :bucket => ENV['S3_BUCKET_NAME'],
      :access_key_id => ENV['AWS_ACCESS_KEY'],
      :secret_access_key => ENV['AWS_SECRET_KEY']
    }
  }
```
You could use config.paperclip_defaults inside an environment file or **application.rb** as well, but I would put this in separate file and require it along the desired env files.

Still trying to figure out a clean solution, because after I did it, I had to use s3 in development env as well*. I'm sure it's not the best one, but it works for now.

(*) The decorators _path_ key without _:rails_root/public_ messes up things running dev env and I didn't want to put dirty methods inside the models just to check if env was dev and modify path string.

**Comment by damianlegawiec** [comment]
@fabiode in future version we will move from this configs keeping paperclip settings - it should be fetched directly from paperclip, not create some strange proxy you have to also remember about

**Comment by fabiode** [comment]
@damianlegawiec nice! This will be amazing!

**Comment by krazedkrish** [comment]
@fabiode thanks for the solutions, @damianlegawiec, we will be eagerly waiting  for the next version.

**Comment by reidcooper** [comment]
I think I may be having the same issue instead its only my Taxon's that are not being picked up from my CDN. They are being displayed from s3 however, its only the taxons that are not being shown from the CDN.
 https://github.com/spree/spree/issues/7573
