### ISSUE TITLE
Overriding Order Prefix

### ISSUE THREAD

**Issue by scanales** [spree/spree#7175]
What would be the preferred way to override the "R" defined in order.rb for something else in 3-0-stable? I've searched around for ways to accomplish this but only found for previous versions "2-0-stable", etc.

**Comment by bradleyprice** [comment]
I'm not sure of the "preferred" way to do this, but you could create another `before_validation` in an `order_decorator` that could handle this.

```
Spree::Order.class_eval do
  before_validation do
    self.number = Spree::Core::NumberGenerator.new(prefix: 'S').send(:generate_permalink, Spree::Order)
  end
end
```

This would basically generate a second number and set it, instead of the initial 'R' prefixed number.

The only implication is that this would create a second read on the Order's table, since it would hit the table to see if the generated number exist.

There's possibly a better solution, not sure off of the top of my head though...

**Comment by scanales** [comment]
Thanks @bradleyprice I tried that but `Spree::Core::NumberGenerator` throws uninitialized constant error. I got it to work with Spree::NumberGenerator but then I get `no method error`. Any ideas? I see `Spree::Core::NumberGenerator.new` in many places along the source code: https://github.com/spree/spree/search?utf8=%E2%9C%93&q=numbergenerator but not sure why I'm getting these errors.

**Comment by bradleyprice** [comment]
@scanales I completely missed you stating that you were using the 3-0-stable branch. This would have worked for what's currently in master.

However, for 3-0-stable, you can see this line: https://github.com/spree/spree/blob/3-0-stable/core/app/models/concerns/spree/number_generator.rb#L10, so you could easily do something similar as above, by doing this:

```
Spree::Order.class_eval do
  before_validation(on: :create) do
    generate_number(prefix: 'S')
  end
end
```

There is the possibility that this needs a bit of tweaking, since I don't have 3-0-stable running on my box.

Hope this helps.

**Comment by scanales** [comment]
For some reason it doesn't change the value, but I could do something like `number.sub!("R", "X")`. Not sure if that's the best way though.

**Comment by bradleyprice** [comment]
@scanales Yep, that's because the `generate_number` is using `number ||=`.

In the above before_validation block, you could simply set number to nil before running the `generate_number` to fix that.

```
Spree::Order.class_eval do
  before_validation(on: :create) do
    number = nil
    generate_number(prefix: 'S')
  end
end
```

**Comment by scanales** [comment]
@bradleyprice Thanks for all your help. Needed to add `self.`, otherwise it would't do the change.

**Comment by bradleyprice** [comment]
Ah!

**Comment by bonekost** [comment]
Hey, can you tell me please what about v 3-1?
There is nothing like method generate_number.
Thanks
