### ISSUE TITLE
Order state from payment to address when applying a coupon leading total <= 0.00 

### ISSUE THREAD

**Issue by antoineayoub** [spree/spree#7450]
Hey everyone, 

I have an issue during the checkout flow. With a new user If he applies a coupon with a value >= to the **total** the state go back to the state **address** (so to the address asking page). This is because of the payment_required? function.

In the Order model the checkout flow works as follow :

``` ruby
    checkout_flow do
      go_to_state :address
      go_to_state :delivery
      go_to_state :payment, if: ->(order) { order.payment_required? }
      go_to_state :confirm, if: ->(order) { order.confirmation_required? }
      go_to_state :complete
      remove_transition from: :delivery, to: :confirm
    end
```

It normally should update the status to **complete** state in that case. What do you suggest to manage that ?

**Comment by dajvido** [comment]
I'm working on fix for this issue - stay tuned 🤔

**Comment by dajvido** [comment]
Quick update to let you know it's in progress.

1. Adding promo code which decrease order total to 0 remove payment step - we don't want to require a credit card for a free order (case when promo code is applied in the cart).
2. Spree because of reason trigger checking steps on entering and on leaving every checkout step. In our case when we are leaving payment step our order doesn't contain this step anymore in `checkout_steps` list (because of 1.) and `unknown_state?` returns `true` so we are redirected to the first checkout step available which is `address` - it's a functionality to disallow completing orders which were unpaid completely like when we wanted to buy something for $100 but we have only $20 available.

I'm working further on a fix in here.
