### ISSUE TITLE
Removing delivery step from checkout skips shipping address also in spree + rails

### ISSUE THREAD

**Issue by dinshawr** [spree/spree#7549]
When I write  `remove_checkout_step :delivery` in order_decorator.rb it removes **Shipping Address** info from my `checkout/address` page in spree3-1 stable branch. My requirement is just to skip checkout step 3 page i.e given in image 

[![enter image description here](http://i.stack.imgur.com/WJsHS.png)](http://i.stack.imgur.com/WJsHS.png)

 Please guide me how to overcome with this issue.

**Comment by krtschmr** [comment]
Sowhat you actually want is `select_default_shipping_method
i messed up with that a lot of times :-)


`#order_decorator.rb
  def select_default_shipping
    create_proposed_shipments
    shipments.find_each &:update_amounts
    update_totals
  end
`


`#order_updater_decorator.rb

Spree::OrderUpdater.class_eval do 
  def update
    order.select_default_shipping
    update_totals
    if order.completed?
      update_payment_state
      update_shipments
      update_shipment_state
      update_shipment_total
    end    
    run_hooks
    persist_totals
  end
end

`



`#checkout_controller.rb

Spree::CheckoutController.class_eval do

 def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map(&:to_package)
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)

    # only 1 paymentmethod? (Banktransfer)
    # select it!
    @order.select_default_payment unless @order.payment_required?

    #we select the shipping for the user
    @order.select_default_shipping
    @order.next

    #default logic for finalizing unless he can't select payment_method
    if @order.completed?
      session[:order_id] = nil
      flash.notice = Spree.t(:order_processed_successfully)
      flash[:commerce_tracking] = "nothing special"

      return redirect_to completion_route
    else
      return redirect_to checkout_state_path(@order.state)
    end

  end

end
`
you could also do something like `select_default_shipping if order.onlly_one_shipping_method_available?` because it's useless to select something if you can't avoid id.

feel free to improve the code.

**Comment by mauazua** [comment]
hi @dinshawr, did @krtschmr advice help to solve your problem?

**Comment by Ruxton** [comment]
@mauazua  I can confirm this will skip the shipping step but still drop stock counts (unlike `remove_checkout_step :delivery`)

**Comment by Qwertie-** [comment]
I think this might have changed in a newer version of spree because I can remove address and delivery individually now.

**Comment by jhovad** [comment]
@krtschmr  thank you for your useful code ... I have spent already 5 hours trying to figure out where is the shipping_method selected ... I need adjust **select_default_shipping** somehow because I would like to set shipping based on the order attributes (based on selected payment_method ... free of charge shipping for payment by card, shipping with a small fee for _"cash on delivery"_ payment). Can you hint me where I can set/select the shipping_method? I tried to inspect everything around **create_proposed_shipments** but with no success :-( Thank you very, very much!

**Comment by kinduff** [comment]
This still happens, any guidance of how to approach it?

**Comment by krtschmr** [comment]
we still used it this way.

**Comment by kinduff** [comment]
Still works good, tested with 3-4-stable

**Comment by kinduff** [comment]
@krtschmr 
Code above it's giving me troubles in `3-4-stable` if the user makes the following:
1. Add item to cart
2. Click checkout
3. Checkout as guest
4. Go back to cart
5. Empty cart
6. Add new item to cart

This will raise an exception when the method `create_proposed_shipments` is called, specifically this line: `self.shipments = Spree::Stock::Coordinator.new(self).shipments`.

I was able to patch this modifying the empty action for the cart in the orders controller as follow:
```ruby
Spree::OrdersController.class_eval` do
  def empty
    @order.destroy! if @order = current_order
    redirect_to spree.cart_path
  end
end
```
Would love to discuss outside this issue, wanna talk @ Slack?

**Comment by krtschmr** [comment]
no idea. sounds like there should not be an exception, but who knows. i'm not doing any spree at the moment and the project where it runs is not in my hands (they also never upgraded  so it's 3-2 for sure).

i think spree-core should have this functionality. if there is only 1 shipping method, it doesnt actually make any sense to display it and let the user *confirm* it. it's another step and gives the user the chance to leave the checkout.

what would be the best approach?
