### ISSUE TITLE
Question: State of API V2?

### ISSUE THREAD

**Issue by hhff** [spree/spree#7594]
Hi All!

I'm about to resurrect my lib Spree AMS (https://github.com/hhff/spree_ams) for a project I'm working on (against the Rails 5, Spree 3.2.0.beta.1 release), but wanted to first ask the state of the Spree v2 API.

If there's anyway I can help with that effort, or repurpose the work I've done in Spree AMS, I'd love to lend a hand!

cc @BenMorganIO

**Comment by damianlegawiec** [comment]
AMS isn't stable enough ( https://github.com/rails-api/active_model_serializers#status-of-ams ) we're moving all of our efforts for API v2 into jbuilder.

You can track progress in this (epic) issue -> https://github.com/spree/spree/issues/8288

**Comment by BenMorganIO** [comment]
I would strongly discourage using JBuilder and pursue AMS with a lock on 0.10.x. The reasoning for changing up the API in the first place was because of performance issues. By moving to JBuilder, yes, the syntax gets better, but the primary issue remains unresolved.

Spree will also lose the ability to output to JSON API which is what many individuals still want. I know GraphQL is still picking up steam, but [after a poll](https://github.com/ryal/ryal/issues/23) it looks like the JSON API is twice as popular.

It's highly unrecommended what you're doing since this doesn't resolve the performance concerns, but since Spree is now yours, you may do as you wish.

**Comment by hhff** [comment]
It would be great to do a proper RFC process here - there's plenty of folks out there who love Spree but don't love westling with the API v1!

I would guess most folks these days are looking for a "machine readable" format, rather than a classic API style - something friendlier to FE frameworks than the current format.  

Using AMS & JSON:API would solve for that, but if we're not going that direction, I'm sure many from the Spree community would like to at least have a chance to discuss the direction & key innovations for v2~!

**Comment by damianlegawiec** [comment]
@BenMorganIO @hhff we're not fully settled with the selected tech, but AMS development roadmap and their versioning is completely off. 1 year ago it looked like a perfect fit, but currently - it would be highly dangerous to base the entire platform on this library. We at Spark were huge AMS users and we share your pain but for an e-commerce framework like Spree that powers thousands of retailers we need to choose safe tech that won't result in numerous breaking changes and rewrites in the future.

**Comment by hhff** [comment]
Rad!  Totally understand & makes sense.  

I'm more interested to know what the core innovation of the work would be?  Would it be emulate JSON:API?  Would it be to refactor the checkouts API?  etc.  I'd love to see a formal RFC for the work!
