### ISSUE TITLE
Incremental Order number

### ISSUE THREAD

**Issue by bonekost** [spree/spree#7673]
Hey I would like to ask if its possible to make order number incremental.
Many thanks for any advice.

**Comment by mauazua** [comment]
hi, @bonekost. Generating incremented numbers is not available by default. If you wish, you could override the default behavior in your application to generate numbers in that way. 

However, this is highly unrecommended because of security reasons. If you increment order numbers you let everyone know, how many orders you have in your database and it's easier to guess what id they have. If someone would like to reach for your orders data, he knows exactly, where to hit. 

Thus I would strongly encourage you to leave the numbers randomized.

**Comment by bonekost** [comment]
hi @mauazua many thanks for fast response. I would like to increment lets say just 4 last digits and first 5 or 6 would be random, so I don't think it could be security problem. I need it because of tax and law in my country.

**Comment by mauazua** [comment]
but will you not expose your order's id in that way?
If you are sure you want to manipulate those numbers, you will want to take a look at this class [here](https://github.com/spark-solutions/spree/blob/master/core/lib/spree/core/number_generator.rb). It takes care of generating all the numbers used in spree (orders, shipments, returns, etc.). If you want to change numbers only for orders, you should override adequate methods only for `Spree::Order` class.

**Comment by bonekost** [comment]
No I don't expose order's ID. So how should I exactly override class NumberGenerator? Or how should I override /lib/spree/core/number_generator.rb?
thanks

**Comment by mauazua** [comment]
try to put this under this path: `app/models/spree/core/number_generator_decorator.rb` note the `_decorator.rb` and you should put whole class name in your file, like this:
```
Spree::Core::NumberGenerator.class_eval do
  # some stuff here
end
```

**Comment by mauazua** [comment]
But you shouldn't override the `Spree::Core::NumberGenerator` directly - you will affect generating numbers in every model that uses this class. You should make changes in `Spree::Order` class.

**Comment by bonekost** [comment]
many thanks
it works... and it is OK for me to change number_generator for all models
