### ISSUE TITLE
Product could not be deleted, Spree 3.1

### ISSUE THREAD

**Issue by an9949an** [spree/spree#7760]
Hello!
I installed Rails 4.2.6 + Spree 3.1.3.
When I try to delete any product which was ordered I see message: "Product could not be deleted". Order can be in any status, it does not affect on this issue. This issue reproduced in the standard generated by "rails g spree:install" app with no changes.
Spree 3.2.0.rc1 does not have this issue.
My gemfile(but I tried to change rails version to 4.2.7.1 and spree to 3.1.2, same situation):

`gem 'rails', '4.2.6'`
`gem 'sqlite3'`
`gem 'sass-rails', '~> 5.0'`
`gem 'uglifier', '>= 1.3.0'`
`gem 'coffee-rails', '~> 4.1.0'`
`gem 'jquery-rails'`
`gem 'turbolinks'`
`gem 'jbuilder', '~> 2.0'`
`gem 'sdoc', '~> 0.4.0', group: :doc`
`gem 'spree', '~> 3.1.0'`
`gem 'spree_auth_devise', '~> 3.1.0'`
`gem 'spree_gateway', '~> 3.1.0'`

**Comment by priyank-gupta** [comment]
@an9949an This error is intended and is generated from https://github.com/spree/spree/blob/master/core/app/models/spree/product.rb#L31.

Its not in Spree.3.2.0.rc1 because we missed `throw(:abort)` in `#ensure_no_line_items` callback. I have created a PR to fix this https://github.com/spree/spree/pull/7768.

Thanks for raising this issue.

**Comment by an9949an** [comment]
@priyank-gupta,
Thank you!

**Comment by an9949an** [comment]
@priyank-gupta,
I dont know, should I close this issue now?

**Comment by priyank-gupta** [comment]
@an9949an Closing this.
