### ISSUE TITLE
Ruby version in .ruby-version does not match .rubocop.yml

### ISSUE THREAD

**Issue by artplan1** [spree/spree#8600]
## Context

.ruby-version file defines ruby 2.4.2
.rubocop.yml defines ruby 2.2

Maybe there is a reason for this?

## Expected Behavior

Use one version

**Comment by bbonislawski** [comment]
We support ruby 2.2+ so we cannot enforce style of higher version of ruby. On the other hand, we want to support newest version ruby too, so we use it circle CI to run tests with newest version(will update to 2.5 soon). Rubocop enforces us to write valid ruby for 2.2 too.

Closing this for now since we have to support oldest(2.2) and the most recent(2.5 atm)
