### ISSUE TITLE
ActiveRecord::StatementInvalid in Spree::Admin::Orders#index

### ISSUE THREAD

**Issue by jrnk** [spree/spree#9334]
When using `spree_globalize` and `spree_i18n` and adding another `supported_locale` current version throws an `ActiveRecord::StatementInvalid` on `admin/orders#index` at line 134

## Expected Behavior
The `admin/orders#index` page should render

## Actual Behavior
It throws an `ActiveRecord::StatementInvalid`

## Possible Fix
Adding a `.joins(:translations)` on line https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/orders/index.html.erb#L134 fixes the issue. But seems to be a fix that would only be relevant when using the globalize / i18n packages.

## Steps to Reproduce
1. Add `spree_globalize` and `spree_i18n` gems to basic spree project
2. Add extra locale in initializer, f.e.:
```
SpreeI18n::Config.available_locales = [:en, :fr]
SpreeGlobalize::Config.supported_locales = [:en, :fr]
```
3. Open up `/admin/orders`

## Your Environment
```
spree_globalize (3.4.0)
spree_i18n (3.3.2)
spree (3.7.1)
rails (>= 5.2.1.1)
```

**Comment by rafalcymerys** [comment]
We ran into the same issue.
The problem was that the order statement specifies table name explicitly. Globalize gem replaces references to translated columns with joins to translations table. In the resulting query name for the select clause is pulled from translations table, whereas name in order clause from store table (as its specified explicitly).

What helped was replacing `Spree::Store.order("#{Spree::Store.table_name}.name").pluck(:name, :id)` with `Spree::Store.order(:name).pluck(:name, :id)` in line #134 of `orders/index.html`.

**Comment by damianlegawiec** [comment]
Hey @rafalcymerys 

Would you mind creating a PR with a fix? Thank you!

**Comment by rafalcymerys** [comment]
Sure, I'll do that later this week
