### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by CharlyJazz** [spree/spree#9390]
## Context
Is this a vulnerability?

I am writing a script in the `description` field in the admin product form

## Expected Behavior
Sanitize data

## Actual Behavior
A hackerman alert

## Possible Fix
`html_safe` Maybe?

## Steps to Reproduce
Just see my screenshots

## Your Environment
``` ruby
ruby '2.4.2'
gem 'rails', '~> 5.2.3'
gem 'spree', '~> 3.7'
```

## Screenshots
![Screenshot from 2019-05-01 01-06-39](https://user-images.githubusercontent.com/12489333/57005306-69336180-6bad-11e9-9752-426edb0f1b61.png)
![Screenshot from 2019-05-01 01-06-31](https://user-images.githubusercontent.com/12489333/57005307-69336180-6bad-11e9-98a6-1d6cc0825ca4.png)

**Comment by damianlegawiec** [comment]
@CharlyJazz 

On one hand, this shouldn't be treated as XSS Vulnerability because only the admin users can edit the description. On the other hand, you can have different roles with limited access to the admin panel so this could be dangerous. 

Would you mind creating a PR to master branch with a fix? We will later backport it to older Spree versions. 

This will probably break https://github.com/spree-contrib/spree_editor so we also will need modify that extension. 

Thanks!
