### ISSUE TITLE
Access to a discounted product price

### ISSUE THREAD

**Issue by sofianegargouri** [spree/spree#9720]
**Describe the solution you'd like**
Some promotions can be displayed on a product, like `Spree::Promotion::Rules::Taxon`,  `Spree::Promotion::Rules::Product` or `Spree::Promotion::Rules::UserLoggedIn`

**Describe alternatives you've considered**

I have a store with a Category A, for which I created a 15% discount on all its articles.
All of those articles should be able to be displayed on the store with their original price and their 15% discount price, like this:

![image](https://user-images.githubusercontent.com/4323986/71547169-c41b9380-299c-11ea-8479-b15ac39f930d.png)

Is there any temporary workaround to do this ?

**Comment by sofianegargouri** [comment]
@damianlegawiec Is there any temporary solution to achieve this ? 🤔

**Comment by NetViz** [comment]
You have two price file in backend (cost price & master) why can't you find a difference between both and show it on frontend.

Master Price - 10
Cost Price - 20
You Save - 10(50%)

**Comment by NetViz** [comment]
![Screenshot_2020-03-08-12-11-46-48](https://user-images.githubusercontent.com/60209134/76157936-1d8b0600-6136-11ea-87ab-708378a46170.png)

**Comment by sofianegargouri** [comment]
The cost price is already used to store at which price the product has been bought. Furthermore, I have 8 000+ products, and we’re doing promotions using the Spree filters. We can’t afford to apply manually a promotion price.

**Comment by tegandbiscuits** [comment]
I hate to reply to an issue without really contributing much, but I'm in a similar situation. I have a promotion set up in Spree that works as intended, but I'm trying to make it so the discounted price is shown on the product page instead of after it's added to the cart.

It seems like there should be something to find applicable promotions for a given product without it needing to be in the cart, but I didn't find anything obvious when I looked. Though not being super familiar with the inner workings of Spree, maybe this is a more complex thing than I imagine?

**Comment by damianlegawiec** [comment]
Compare At / Discount price was added to Spree 4.2
